### ISSUE TITLE
Switches and Machines are the Same Object

### ISSUE THREAD

**Issue by eatnumber1** [cohoe/starrs-web#28]
In the web view, switches and machines are grouped together I find this to be unintuitive. Also a switch's VLAN has an icon as if it's an ethernet card.

**Comment by cohoe** [comment]
As far as the database is concerned, network devices are included as systems since they have all of the same child objects as computer systems. "VLAN49" is just the name I gave to the interface and has no bearing on any actual VLANs on the switch. Since this switch has been removed, there will be a new object for it with two interfaces, "49net","50net" which will correspond to each of the switch virtual interfaces (49.247, 50.247). However i have added a seperate category for network devices. We'll see how it works out.
