### ISSUE TITLE
Menu options derped after DNS record deletion

### ISSUE THREAD

**Issue by clockfort** [cohoe/starrs-web#36]
After a DNS record has been successfully deleted, the menu at top displays a "cancel" button (which is useless since it is already deleted at this point) and all of the other wanted options (adding a new DNS entry, etc) are hidden until the page is re-navigated to.

**Comment by cohoe** [comment]
The reason for this is because clicking the initial "Delete" button puts you in a "Delete Mode", where you can easily delete multiple records if they exist. If you only have one record, then yes it is sort of derpy. However it was designed with the intention to prevent you from having to click "Delete->X->Delete->X->Delete->X" to remove 3 records rather than "Delete->X->X->X".
