### ISSUE TITLE
Deprecated function in use

### ISSUE THREAD

**Issue by cohoe** [cohoe/starrs-web#55]
A PHP Error was encountered

Severity: 8192

Message: Function split() is deprecated

Filename: objects/PointerRecord.php

Line Number: 52

**Comment by benrr101** [comment]
%s/split(/explode(/

Basically explode takes a char to split the string by and the string to split. It returns an array (which is what you want since you're using the list operator). The inverse function is implode which takes a 'glue' string and an array of 'pieces'.

I'd do a pull request but I'm not really in a setting that will allow me to do so...

**Comment by cohoe** [comment]
This issue is superceded by #57 since the only use of split() is in a class that will no longer exist once v2 is completed. PointerRecord will be replaced with SrvRecord and CnameRecord and will no longer need the split() function for the "extra" field which I knew was a bad idea to do when I wrote all this, but I did it anyway...
